generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      CommunityFeature
    theme:            default
    list:
      title: Community Feature List
      display: [name]
      filters: [name]
      object_actions:
        _edit: false
        _delete: false

    edit:
      title: Edit Community Feature
      display: [name]