generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      ApartmentFeature
    theme:            default
    list:
      title: Apartment Feature List
      display: [name]
      filters: [name]
      object_actions:
        _edit: false
        _delete: false

    edit:
      title: Edit Apartment Feature
      display: [name]