generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      PropertyFloorplan
    theme:            default
    list:
      title: Property Floorplan List
      display: [name, property, bedrooms, price, lease_term]
      filters: [name]
      object_actions:
        _edit: false
        _delete: false

    edit:
      title: Edit Property Floorplan
      fields:
        image: { type: admin_input_file_tag, upload_dir: floorplans, params: include_link=floorplans include_remove=true}
      display: [name, property_id, bedrooms, bathrooms, square_feet, price, lease_term, deposit, image]