propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  apartment_feature:
    _attributes: { phpName: ApartmentFeature }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '255', required: true, defaultValue: '' }
  community_feature:
    _attributes: { phpName: CommunityFeature }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '255', required: true, defaultValue: '' }
  contact:
    _attributes: { phpName: Contact }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    first_name: { type: VARCHAR, size: '128', required: false }
    last_name: { type: VARCHAR, size: '128', required: false }
    employer: { type: VARCHAR, size: '255', required: false }
    email: { type: VARCHAR, size: '255', required: false }
    created_at: { type: TIMESTAMP, required: false }
    updated_at: { type: TIMESTAMP, required: false }
    property_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: property, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    occupants: { type: VARCHAR, size: '48', required: false }
    pets: { type: VARCHAR, size: '48', required: false }
    when: { type: VARCHAR, size: '128', required: false }
    bedrooms: { type: VARCHAR, size: '48', required: false }
    howhear: { type: VARCHAR, size: '48', required: false }
    howcontact: { type: VARCHAR, size: '48', required: false }
    notes: { type: LONGVARCHAR, required: false }
    phone: { type: VARCHAR, size: '48', required: false }
    fax: { type: VARCHAR, size: '48', required: false }
    corporate_group_id: { type: INTEGER, size: '10', required: true, defaultValue: '1', foreignTable: corporate_group, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    _indexes: { property_id: [property_id], corporate_group_id: [corporate_group_id] }
  corporate_group:
    _attributes: { phpName: CorporateGroup }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '30', required: true, defaultValue: '' }
  other_feature:
    _attributes: { phpName: OtherFeature }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
  photo_type:
    _attributes: { phpName: PhotoType }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '30', required: true, defaultValue: '' }
  property:
    _attributes: { phpName: Property }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    code: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    name: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    address: { type: VARCHAR, size: '128', required: true, defaultValue: '' }
    city: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    state_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: state, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    zip: { type: VARCHAR, size: '20', required: true, defaultValue: '' }
    phone: { type: VARCHAR, size: '20', required: true, defaultValue: '' }
    fax: { type: VARCHAR, size: '20', required: true, defaultValue: '' }
    email: { type: VARCHAR, size: '128', required: true, defaultValue: '' }
    image: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    url: { type: VARCHAR, size: '150', required: true, defaultValue: '' }
    price_range: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    unit_type: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    special: { type: VARCHAR, size: '100', required: true, defaultValue: '' }
    mercial: { type: VARCHAR, size: '150', required: true, defaultValue: '' }
    description: { type: LONGVARCHAR, required: true }
    hours: { type: LONGVARCHAR, required: true }
    pet_policy: { type: LONGVARCHAR, required: true }
    directions: { type: LONGVARCHAR, required: true }
    featured: { type: BOOLEAN, size: '1', required: true, defaultValue: '0' }
    status_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: status, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    corporate_group_id: { type: INTEGER, size: '10', required: true, defaultValue: '1', foreignTable: corporate_group, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    _indexes: { state_id: [state_id], city: [city], url: [url], status_id: [status_id], corporate_group_id: [corporate_group_id] }
  property_apartment_feature:
    _attributes: { phpName: PropertyApartmentFeature }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    property_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: property, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    apartment_feature_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: apartment_feature, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    _indexes: { property_id: [property_id], apartment_feature_id: [apartment_feature_id] }
  property_community_feature:
    _attributes: { phpName: PropertyCommunityFeature }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    property_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: property, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    community_feature_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: community_feature, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    _indexes: { property_id: [property_id], community_feature_id: [community_feature_id] }
  property_community_map:
    _attributes: { phpName: PropertyCommunityMap }
    id: { phpName: Id, type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    property_id: { phpName: PropertyId, type: INTEGER, size: '10', required: true }
    type: { phpName: Type, type: CHAR, required: true, defaultValue: entertainment }
    name: { phpName: Name, type: VARCHAR, size: '128', required: false }
    latitude: { phpName: Latitude, type: DECIMAL, size: '10', scale: '6', required: false }
    longitude: { phpName: Longitude, type: DECIMAL, size: '10', scale: '6', required: false }
    url: { phpName: Url, type: VARCHAR, size: '255', required: false }
    _indexes: { property_id: [property_id] }
  property_floorplan:
    _attributes: { phpName: PropertyFloorplan }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    property_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: property, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    name: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    bedrooms: { type: INTEGER, size: '10', required: true, defaultValue: '' }
    bathrooms: { phpName: Bathrooms, type: VARCHAR, size: '16', required: true, defaultValue: '0' }
    square_feet: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    price: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    lease_term: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    deposit: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    image: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    availability_link: { type: VARCHAR, size: '255', required: true, defaultValue: '' }
    display_order: { type: INTEGER, size: '10', required: true, defaultValue: '0' }
    _indexes: { property_id: [property_id] }
  property_neighborhood:
    _attributes: { phpName: PropertyNeighborhood }
    id: { phpName: Id, type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    property_id: { phpName: PropertyId, type: INTEGER, size: '10', required: true }
    name: { phpName: Name, type: VARCHAR, size: '128', required: true, defaultValue: '' }
    description: { phpName: Description, type: LONGVARCHAR, required: true }
    url: { phpName: Url, type: VARCHAR, size: '255', required: false }
    image: { phpName: Image, type: VARCHAR, size: '50', required: true, defaultValue: '' }
    _indexes: { property_id: [property_id] }
  property_other_feature:
    _attributes: { phpName: PropertyOtherFeature }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    property_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: property, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    other_feature_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: other_feature, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    _indexes: { property_id: [property_id], community_feature_id: [other_feature_id] }
  property_photo:
    _attributes: { phpName: PropertyPhoto }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    property_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: property, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    name: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    image: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    photo_type_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: photo_type, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    display_order: { type: INTEGER, size: '10', required: true, defaultValue: '0' }
    _indexes: { property_id: [property_id], photo_type_id: [photo_type_id] }
  property_blogarticle:
    _attributes: { phpName: PropertyBlogarticle }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    property_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: property, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    title: { type: VARCHAR, size: '255', required: false }
    perma_link: { type: VARCHAR, size: '255', required: false }
    article_image1: { type: VARCHAR, size: '50', required: false }
    article_image2: { type: VARCHAR, size: '50', required: false }
    article_content: { type: LONGVARCHAR, required: false }
    _indexes: { property_id: [property_id] }
  property_template:
    _attributes: { phpName: PropertyTemplate }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    property_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: property, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    logo_image: { type: VARCHAR, size: '50', required: false }
    home_image: { type: VARCHAR, size: '50', required: false }
    welcome: { type: VARCHAR, size: '255', required: false }
    description: { type: LONGVARCHAR, required: false }
    announcements: { type: LONGVARCHAR, required: false }
    style_color: { type: VARCHAR, size: '10', required: false }
    background_color: { type: VARCHAR, size: '10', required: false }
    chat: { type: LONGVARCHAR, required: false }
    rentalapp_file: { type: VARCHAR, size: '50', required: false }
    map_html: { type: LONGVARCHAR, required: false }
    map_frame_src: { type: LONGVARCHAR, required: false }
    community_image: { type: VARCHAR, size: '50', required: false }
    community_description: { type: LONGVARCHAR, required: false }
    community_attractions_list: { type: LONGVARCHAR, required: false }
    custom_page_name: { type: VARCHAR, size: '128', required: false }
    custom_page_perma_link: { type: VARCHAR, size: '255', required: false }
    custom_page_content: { type: LONGVARCHAR, required: false }
    home_flash: { type: VARCHAR, size: '50', required: false }
    tracking_code: { type: LONGVARCHAR, required: false }
    contact_email_text: { type: LONGVARCHAR, required: false }
    show_walkscore: { type: BOOLEAN, size: '1', required: true, defaultValue: '1' }
    email: { type: LONGVARCHAR, required: false }
    facebook_url: { type: LONGVARCHAR, required: false }
    acacia_home1_desc: { type: VARCHAR, size: '64', required: false }
    acacia_features_desc: { type: LONGVARCHAR, required: false }
    acacia_home2_desc: { type: VARCHAR, size: '64', required: false }
    acacia_home3_desc: { type: VARCHAR, size: '64', required: false }
    acacia_floorplan_desc: { type: LONGVARCHAR, required: false }
    acacia_ebrochure_desc: { type: LONGVARCHAR, required: false }
    latitude: { phpName: Latitude, type: DECIMAL, size: '10', scale: '6', required: false }
    longitude: { phpName: Longitude, type: DECIMAL, size: '10', scale: '6', required: false }
    online_application_url: { type: LONGVARCHAR, required: false }
    e_brochure: { type: VARCHAR, size: '50', required: false }
    online_application_url: { type: LONGVARCHAR, required: false }
    src_3dtour: { type: LONGVARCHAR, required: false }
    home_photo_desc: { type: LONGVARCHAR, required: false }
    gmap_key: { type: LONGVARCHAR, required: false }
    _indexes: { property_id: [property_id] }
  resident:
    _attributes: { phpName: Resident }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    first_name: { type: VARCHAR, size: '128', required: true, defaultValue: '' }
    last_name: { type: VARCHAR, size: '128', required: true, defaultValue: '' }
    password: { type: VARCHAR, size: '255', required: true, defaultValue: '' }
    email: { type: VARCHAR, size: '255', required: true, defaultValue: '' }
    tenantid: { type: VARCHAR, size: '24', required: true, defaultValue: '' }
    created_at: { type: TIMESTAMP, required: false }
    updated_at: { type: TIMESTAMP, required: false }
    property_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: property, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    status_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: status, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    _indexes: { property_id: [property_id], status_id: [status_id] }
  state:
    _attributes: { phpName: State }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '50', required: true, defaultValue: '' }
    code: { type: VARCHAR, size: '2', required: true, defaultValue: '' }
    country: { type: VARCHAR, size: '3', required: true, defaultValue: '' }
    order_by: { type: INTEGER, size: '11', required: true, defaultValue: '' }
    _indexes: { code: [code] }
  status:
    _attributes: { phpName: Status }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '30', required: true, defaultValue: '' }
  user:
    _attributes: { phpName: User }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    username: { type: VARCHAR, size: '30', required: true, defaultValue: '' }
    password: { type: VARCHAR, size: '255', required: true, defaultValue: '' }
    email: { type: VARCHAR, size: '255', required: true, defaultValue: '' }
    name: { type: VARCHAR, size: '255', required: false }
    created_at: { type: TIMESTAMP, required: false }
    updated_at: { type: TIMESTAMP, required: false }
    _uniques: { username: [username] }
  user_property:
    _attributes: { phpName: UserProperty }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    user_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: user, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    property_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: property, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    _indexes: { user_id: [user_id], property_id: [property_id] }
  user_role:
    _attributes: { phpName: UserRole }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    role_name: { type: VARCHAR, size: '30', required: true, defaultValue: '' }
    _uniques: { role_name: [role_name] }
  user_user_role:
    _attributes: { phpName: UserUserRole }
    id: { type: INTEGER, size: '10', primaryKey: true, autoIncrement: true, required: true }
    user_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: user, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    user_role_id: { type: INTEGER, size: '10', required: true, defaultValue: '', foreignTable: user_role, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    _indexes: { user_id: [user_id], user_role_id: [user_role_id] }
  zip_code:
    _attributes: { phpName: ZipCode }
    zip_code: { type: VARCHAR, size: '5', primaryKey: true, required: true }
    zip_code_type: { type: VARCHAR, size: '32', required: true }
    city: { type: VARCHAR, size: '128', required: true }
    state: { type: VARCHAR, size: '4', required: true }
    location_type: { type: VARCHAR, size: '32', required: true }
    lat: { type: DECIMAL, size: '10', scale: '2', required: true }
    long: { type: DECIMAL, size: '10', scale: '2', required: true }
    location: { type: VARCHAR, size: '32', required: true }
    decommisioned: { type: VARCHAR, size: '12', required: true }
    tax_returns_filed: { type: INTEGER, size: '11', required: false }
    estimated_population: { type: INTEGER, size: '11', required: false }
    total_wages: { type: INTEGER, size: '11', required: false }
    _indexes: { state: [state], lat: [lat], long: [long] }
