<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:36:41
sfConfig::add(array(
  'mod_about_enabled' => true,
  'mod_about_view_class' => 'sfPHP',
  'mod_about_is_internal' => false,
));
