<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:13:47
sfConfig::add(array(
  'mod_llcproperty_enabled' => true,
  'mod_llcproperty_view_class' => 'sfPHP',
  'mod_llcproperty_is_internal' => false,
));
