<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:20:17
sfConfig::add(array(
  'mod_bloomingdale_enabled' => true,
  'mod_bloomingdale_view_class' => 'sfPHP',
  'mod_bloomingdale_is_internal' => false,
));
