<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:38:07
sfConfig::add(array(
  'mod_privacypolicy_enabled' => true,
  'mod_privacypolicy_view_class' => 'sfPHP',
  'mod_privacypolicy_is_internal' => false,
));
