<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 11:01:10
sfConfig::add(array(
  'mod_corporatehousing_enabled' => true,
  'mod_corporatehousing_view_class' => 'sfPHP',
  'mod_corporatehousing_is_internal' => false,
));
