<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:38:23
sfConfig::add(array(
  'mod_contactus_enabled' => true,
  'mod_contactus_view_class' => 'sfPHP',
  'mod_contactus_is_internal' => false,
));
