<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:58:48
sfConfig::add(array(
  'mod_employment_enabled' => true,
  'mod_employment_view_class' => 'sfPHP',
  'mod_employment_is_internal' => false,
));
