<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/03 03:38:14
sfConfig::add(array(
  'mod_movingresources_enabled' => true,
  'mod_movingresources_view_class' => 'sfPHP',
  'mod_movingresources_is_internal' => false,
));
