<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:23:38
sfConfig::add(array(
  'mod_seniorliving_enabled' => true,
  'mod_seniorliving_view_class' => 'sfPHP',
  'mod_seniorliving_is_internal' => false,
));
