<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 11:03:24
sfConfig::add(array(
  'mod_termsofuse_enabled' => true,
  'mod_termsofuse_view_class' => 'sfPHP',
  'mod_termsofuse_is_internal' => false,
));
