<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:11:53
sfConfig::add(array(
  'mod_property_enabled' => true,
  'mod_property_view_class' => 'sfPHP',
  'mod_property_is_internal' => false,
));
