<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:56:18
sfConfig::add(array(
  'mod_findapartment_enabled' => true,
  'mod_findapartment_view_class' => 'sfPHP',
  'mod_findapartment_is_internal' => false,
));
