<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 17:55:46
sfConfig::add(array(
  'mod_apartmentsineverett_enabled' => true,
  'mod_apartmentsineverett_view_class' => 'sfPHP',
  'mod_apartmentsineverett_is_internal' => false,
));
