<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 11:30:26
sfConfig::add(array(
  'mod_sfcaptchagd_enabled' => true,
  'mod_sfcaptchagd_view_class' => 'sfPHP',
  'mod_sfcaptchagd_is_internal' => false,
));
