<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/26 18:01:33

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=amcapartments_com;host=localhost',
  'username' => 'amcapartments',
  'password' => 'Um5AvWNV',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
