<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/26 18:02:06
sfConfig::add(array(
  'mod_community_enabled' => true,
  'mod_community_view_class' => 'sfPHP',
  'mod_community_is_internal' => false,
));
