<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/10/26 18:01:40
$this->security = array (
  'forgotpassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
