<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/26 18:07:38
sfConfig::add(array(
  'mod_ourpage_enabled' => true,
  'mod_ourpage_view_class' => 'sfPHP',
  'mod_ourpage_is_internal' => false,
));
