<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/26 20:38:06
sfConfig::add(array(
  'mod_blog_enabled' => true,
  'mod_blog_view_class' => 'sfPHP',
  'mod_blog_is_internal' => false,
));
