<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/26 18:01:39
sfConfig::add(array(
  'mod_photos_enabled' => true,
  'mod_photos_view_class' => 'sfPHP',
  'mod_photos_is_internal' => false,
));
