<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/26 18:03:17
sfConfig::add(array(
  'mod_features_enabled' => true,
  'mod_features_view_class' => 'sfPHP',
  'mod_features_is_internal' => false,
));
