<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/26 18:02:05
sfConfig::add(array(
  'mod_privacypolicy_enabled' => true,
  'mod_privacypolicy_view_class' => 'sfPHP',
  'mod_privacypolicy_is_internal' => false,
));
