mobileSuccess:
  stylesheets: [-*, http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.css, mobilemain.css]
  javascripts: [-*, http://code.jquery.com/jquery-1.7.1.min.js, http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js, http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js, photos.js]
acaciaSuccess:
  stylesheets: [-*, acacia.css]
  javascripts: [-*, https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, jquery.cycle.all.js, acaciacycle.js]
acaciamobileSuccess:
#  stylesheets: [-*, http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.css, acaciamobile.css]
#  javascripts: [-*, http://code.jquery.com/jquery-1.7.1.min.js, http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js, http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js, acaciamobile.js]
  stylesheets: [-*]
  javascripts: [-*]
jspSuccess:
  stylesheets: [-*, jsp.css]
  javascripts: [-*, https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, jquery.nivo.slider.pack.js, jsp-home.js]
jspmobileSuccess:
  stylesheets: [-*]
  javascripts: [-*]