<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/17 10:15:51
sfConfig::add(array(
  'mod_sfcaptchagd_enabled' => true,
  'mod_sfcaptchagd_view_class' => 'sfPHP',
  'mod_sfcaptchagd_is_internal' => false,
));
