<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/17 10:15:50
sfConfig::add(array(
  'mod_contact_enabled' => true,
  'mod_contact_view_class' => 'sfPHP',
  'mod_contact_is_internal' => false,
));
