<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/07/02 11:41:43
sfConfig::add(array(
  'mod_community_enabled' => true,
  'mod_community_view_class' => 'sfPHP',
  'mod_community_is_internal' => false,
));
