<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/13 15:02:51
sfConfig::add(array(
  'mod_ebrochure_enabled' => true,
  'mod_ebrochure_view_class' => 'sfPHP',
  'mod_ebrochure_is_internal' => false,
));
