<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/04/01 22:36:23
sfConfig::add(array(
  'mod_termsofuse_enabled' => true,
  'mod_termsofuse_view_class' => 'sfPHP',
  'mod_termsofuse_is_internal' => false,
));
