<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/13 15:04:37
sfConfig::add(array(
  'mod_features_enabled' => true,
  'mod_features_view_class' => 'sfPHP',
  'mod_features_is_internal' => false,
));
