<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/13 15:13:07
sfConfig::add(array(
  'mod_default_enabled' => true,
  'mod_default_view_class' => 'sfPHP',
  'mod_default_is_internal' => false,
));
