default:
  http_metas:
    content-type: text/html

  metas:
    title:        
    description:  
    keywords:     
    language:     
    robots:       


  stylesheets:   ~

  javascripts:    ~

  has_layout:     false
  layout:         