<?php
// auto-generated by sfValidatorConfigHandler
// date: 2017/03/08 15:00:57

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $this->context->getRequest()->setAttribute('symfony.fillin', array (
));
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['sfFileValidator_property_template{community_image}'] = new sfFileValidator($this->context, array (
  'mime_types' => 
  array (
    0 => 'image/jpeg',
    1 => 'image/png',
    2 => 'image/x-png',
    3 => 'image/pjpeg',
    4 => 'image/gif',
  ),
  'mime_types_error' => 'Only images please',
));

  $validatorManager->registerName('community_image', 0, 'Required', 'property_template', null, 1);
  $validatorManager->registerValidator('community_image', $validators['sfFileValidator_property_template{community_image}'], 'property_template');
  $this->context->getRequest()->setAttribute('symfony.fillin', array (
));
}
