<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2017/03/08 14:52:11
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoProperty_floorplans/actions/actions.class.php');

