<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/08 14:28:12
sfConfig::add(array(
  'mod_silent_login_enabled' => true,
  'mod_silent_login_view_class' => 'sfPHP',
  'mod_silent_login_is_internal' => false,
));
