<?php

/**
 * Base class that represents a row from the 'zip_code' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jun 17 21:26:59 2014
 *
 * @package    lib.model.om
 */
abstract class BaseZipCode extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ZipCodePeer
	 */
	protected static $peer;

	/**
	 * The value for the zip_code field.
	 * @var        string
	 */
	protected $zip_code;

	/**
	 * The value for the zip_code_type field.
	 * @var        string
	 */
	protected $zip_code_type;

	/**
	 * The value for the city field.
	 * @var        string
	 */
	protected $city;

	/**
	 * The value for the state field.
	 * @var        string
	 */
	protected $state;

	/**
	 * The value for the location_type field.
	 * @var        string
	 */
	protected $location_type;

	/**
	 * The value for the lat field.
	 * @var        string
	 */
	protected $lat;

	/**
	 * The value for the long field.
	 * @var        string
	 */
	protected $long;

	/**
	 * The value for the location field.
	 * @var        string
	 */
	protected $location;

	/**
	 * The value for the decommisioned field.
	 * @var        string
	 */
	protected $decommisioned;

	/**
	 * The value for the tax_returns_filed field.
	 * @var        int
	 */
	protected $tax_returns_filed;

	/**
	 * The value for the estimated_population field.
	 * @var        int
	 */
	protected $estimated_population;

	/**
	 * The value for the total_wages field.
	 * @var        int
	 */
	protected $total_wages;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ZipCodePeer';

	/**
	 * Get the [zip_code] column value.
	 * 
	 * @return     string
	 */
	public function getZipCode()
	{
		return $this->zip_code;
	}

	/**
	 * Get the [zip_code_type] column value.
	 * 
	 * @return     string
	 */
	public function getZipCodeType()
	{
		return $this->zip_code_type;
	}

	/**
	 * Get the [city] column value.
	 * 
	 * @return     string
	 */
	public function getCity()
	{
		return $this->city;
	}

	/**
	 * Get the [state] column value.
	 * 
	 * @return     string
	 */
	public function getState()
	{
		return $this->state;
	}

	/**
	 * Get the [location_type] column value.
	 * 
	 * @return     string
	 */
	public function getLocationType()
	{
		return $this->location_type;
	}

	/**
	 * Get the [lat] column value.
	 * 
	 * @return     string
	 */
	public function getLat()
	{
		return $this->lat;
	}

	/**
	 * Get the [long] column value.
	 * 
	 * @return     string
	 */
	public function getLong()
	{
		return $this->long;
	}

	/**
	 * Get the [location] column value.
	 * 
	 * @return     string
	 */
	public function getLocation()
	{
		return $this->location;
	}

	/**
	 * Get the [decommisioned] column value.
	 * 
	 * @return     string
	 */
	public function getDecommisioned()
	{
		return $this->decommisioned;
	}

	/**
	 * Get the [tax_returns_filed] column value.
	 * 
	 * @return     int
	 */
	public function getTaxReturnsFiled()
	{
		return $this->tax_returns_filed;
	}

	/**
	 * Get the [estimated_population] column value.
	 * 
	 * @return     int
	 */
	public function getEstimatedPopulation()
	{
		return $this->estimated_population;
	}

	/**
	 * Get the [total_wages] column value.
	 * 
	 * @return     int
	 */
	public function getTotalWages()
	{
		return $this->total_wages;
	}

	/**
	 * Set the value of [zip_code] column.
	 * 
	 * @param      string $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setZipCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->zip_code !== $v) {
			$this->zip_code = $v;
			$this->modifiedColumns[] = ZipCodePeer::ZIP_CODE;
		}

		return $this;
	} // setZipCode()

	/**
	 * Set the value of [zip_code_type] column.
	 * 
	 * @param      string $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setZipCodeType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->zip_code_type !== $v) {
			$this->zip_code_type = $v;
			$this->modifiedColumns[] = ZipCodePeer::ZIP_CODE_TYPE;
		}

		return $this;
	} // setZipCodeType()

	/**
	 * Set the value of [city] column.
	 * 
	 * @param      string $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setCity($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->city !== $v) {
			$this->city = $v;
			$this->modifiedColumns[] = ZipCodePeer::CITY;
		}

		return $this;
	} // setCity()

	/**
	 * Set the value of [state] column.
	 * 
	 * @param      string $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setState($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->state !== $v) {
			$this->state = $v;
			$this->modifiedColumns[] = ZipCodePeer::STATE;
		}

		return $this;
	} // setState()

	/**
	 * Set the value of [location_type] column.
	 * 
	 * @param      string $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setLocationType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->location_type !== $v) {
			$this->location_type = $v;
			$this->modifiedColumns[] = ZipCodePeer::LOCATION_TYPE;
		}

		return $this;
	} // setLocationType()

	/**
	 * Set the value of [lat] column.
	 * 
	 * @param      string $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setLat($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->lat !== $v) {
			$this->lat = $v;
			$this->modifiedColumns[] = ZipCodePeer::LAT;
		}

		return $this;
	} // setLat()

	/**
	 * Set the value of [long] column.
	 * 
	 * @param      string $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setLong($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->long !== $v) {
			$this->long = $v;
			$this->modifiedColumns[] = ZipCodePeer::LONG;
		}

		return $this;
	} // setLong()

	/**
	 * Set the value of [location] column.
	 * 
	 * @param      string $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setLocation($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->location !== $v) {
			$this->location = $v;
			$this->modifiedColumns[] = ZipCodePeer::LOCATION;
		}

		return $this;
	} // setLocation()

	/**
	 * Set the value of [decommisioned] column.
	 * 
	 * @param      string $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setDecommisioned($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->decommisioned !== $v) {
			$this->decommisioned = $v;
			$this->modifiedColumns[] = ZipCodePeer::DECOMMISIONED;
		}

		return $this;
	} // setDecommisioned()

	/**
	 * Set the value of [tax_returns_filed] column.
	 * 
	 * @param      int $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setTaxReturnsFiled($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tax_returns_filed !== $v) {
			$this->tax_returns_filed = $v;
			$this->modifiedColumns[] = ZipCodePeer::TAX_RETURNS_FILED;
		}

		return $this;
	} // setTaxReturnsFiled()

	/**
	 * Set the value of [estimated_population] column.
	 * 
	 * @param      int $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setEstimatedPopulation($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->estimated_population !== $v) {
			$this->estimated_population = $v;
			$this->modifiedColumns[] = ZipCodePeer::ESTIMATED_POPULATION;
		}

		return $this;
	} // setEstimatedPopulation()

	/**
	 * Set the value of [total_wages] column.
	 * 
	 * @param      int $v new value
	 * @return     ZipCode The current object (for fluent API support)
	 */
	public function setTotalWages($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->total_wages !== $v) {
			$this->total_wages = $v;
			$this->modifiedColumns[] = ZipCodePeer::TOTAL_WAGES;
		}

		return $this;
	} // setTotalWages()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->zip_code = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->zip_code_type = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->city = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->state = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->location_type = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->lat = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->long = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->location = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->decommisioned = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->tax_returns_filed = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->estimated_population = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->total_wages = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = ZipCodePeer::NUM_COLUMNS - ZipCodePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating ZipCode object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ZipCodePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ZipCodePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ZipCodePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseZipCode:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ZipCodePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseZipCode:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ZipCodePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseZipCode:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseZipCode:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ZipCodePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ZipCodePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += ZipCodePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = ZipCodePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ZipCodePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getZipCode();
				break;
			case 1:
				return $this->getZipCodeType();
				break;
			case 2:
				return $this->getCity();
				break;
			case 3:
				return $this->getState();
				break;
			case 4:
				return $this->getLocationType();
				break;
			case 5:
				return $this->getLat();
				break;
			case 6:
				return $this->getLong();
				break;
			case 7:
				return $this->getLocation();
				break;
			case 8:
				return $this->getDecommisioned();
				break;
			case 9:
				return $this->getTaxReturnsFiled();
				break;
			case 10:
				return $this->getEstimatedPopulation();
				break;
			case 11:
				return $this->getTotalWages();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ZipCodePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getZipCode(),
			$keys[1] => $this->getZipCodeType(),
			$keys[2] => $this->getCity(),
			$keys[3] => $this->getState(),
			$keys[4] => $this->getLocationType(),
			$keys[5] => $this->getLat(),
			$keys[6] => $this->getLong(),
			$keys[7] => $this->getLocation(),
			$keys[8] => $this->getDecommisioned(),
			$keys[9] => $this->getTaxReturnsFiled(),
			$keys[10] => $this->getEstimatedPopulation(),
			$keys[11] => $this->getTotalWages(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ZipCodePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setZipCode($value);
				break;
			case 1:
				$this->setZipCodeType($value);
				break;
			case 2:
				$this->setCity($value);
				break;
			case 3:
				$this->setState($value);
				break;
			case 4:
				$this->setLocationType($value);
				break;
			case 5:
				$this->setLat($value);
				break;
			case 6:
				$this->setLong($value);
				break;
			case 7:
				$this->setLocation($value);
				break;
			case 8:
				$this->setDecommisioned($value);
				break;
			case 9:
				$this->setTaxReturnsFiled($value);
				break;
			case 10:
				$this->setEstimatedPopulation($value);
				break;
			case 11:
				$this->setTotalWages($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ZipCodePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setZipCode($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setZipCodeType($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCity($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setState($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setLocationType($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setLat($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setLong($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setLocation($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDecommisioned($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setTaxReturnsFiled($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setEstimatedPopulation($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setTotalWages($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ZipCodePeer::DATABASE_NAME);

		if ($this->isColumnModified(ZipCodePeer::ZIP_CODE)) $criteria->add(ZipCodePeer::ZIP_CODE, $this->zip_code);
		if ($this->isColumnModified(ZipCodePeer::ZIP_CODE_TYPE)) $criteria->add(ZipCodePeer::ZIP_CODE_TYPE, $this->zip_code_type);
		if ($this->isColumnModified(ZipCodePeer::CITY)) $criteria->add(ZipCodePeer::CITY, $this->city);
		if ($this->isColumnModified(ZipCodePeer::STATE)) $criteria->add(ZipCodePeer::STATE, $this->state);
		if ($this->isColumnModified(ZipCodePeer::LOCATION_TYPE)) $criteria->add(ZipCodePeer::LOCATION_TYPE, $this->location_type);
		if ($this->isColumnModified(ZipCodePeer::LAT)) $criteria->add(ZipCodePeer::LAT, $this->lat);
		if ($this->isColumnModified(ZipCodePeer::LONG)) $criteria->add(ZipCodePeer::LONG, $this->long);
		if ($this->isColumnModified(ZipCodePeer::LOCATION)) $criteria->add(ZipCodePeer::LOCATION, $this->location);
		if ($this->isColumnModified(ZipCodePeer::DECOMMISIONED)) $criteria->add(ZipCodePeer::DECOMMISIONED, $this->decommisioned);
		if ($this->isColumnModified(ZipCodePeer::TAX_RETURNS_FILED)) $criteria->add(ZipCodePeer::TAX_RETURNS_FILED, $this->tax_returns_filed);
		if ($this->isColumnModified(ZipCodePeer::ESTIMATED_POPULATION)) $criteria->add(ZipCodePeer::ESTIMATED_POPULATION, $this->estimated_population);
		if ($this->isColumnModified(ZipCodePeer::TOTAL_WAGES)) $criteria->add(ZipCodePeer::TOTAL_WAGES, $this->total_wages);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ZipCodePeer::DATABASE_NAME);

		$criteria->add(ZipCodePeer::ZIP_CODE, $this->zip_code);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getZipCode();
	}

	/**
	 * Generic method to set the primary key (zip_code column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setZipCode($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of ZipCode (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setZipCode($this->zip_code);

		$copyObj->setZipCodeType($this->zip_code_type);

		$copyObj->setCity($this->city);

		$copyObj->setState($this->state);

		$copyObj->setLocationType($this->location_type);

		$copyObj->setLat($this->lat);

		$copyObj->setLong($this->long);

		$copyObj->setLocation($this->location);

		$copyObj->setDecommisioned($this->decommisioned);

		$copyObj->setTaxReturnsFiled($this->tax_returns_filed);

		$copyObj->setEstimatedPopulation($this->estimated_population);

		$copyObj->setTotalWages($this->total_wages);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     ZipCode Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ZipCodePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ZipCodePeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseZipCode:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseZipCode::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseZipCode
