<?php

/**
 * Base static class for performing query and update operations on the 'property_template' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jun 17 21:26:58 2014
 *
 * @package    lib.model.om
 */
abstract class BasePropertyTemplatePeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'property_template';

	/** the related Propel class for this table */
	const OM_CLASS = 'PropertyTemplate';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.PropertyTemplate';

	/** the related TableMap class for this table */
	const TM_CLASS = 'PropertyTemplateTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 33;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'property_template.ID';

	/** the column name for the PROPERTY_ID field */
	const PROPERTY_ID = 'property_template.PROPERTY_ID';

	/** the column name for the LOGO_IMAGE field */
	const LOGO_IMAGE = 'property_template.LOGO_IMAGE';

	/** the column name for the HOME_IMAGE field */
	const HOME_IMAGE = 'property_template.HOME_IMAGE';

	/** the column name for the WELCOME field */
	const WELCOME = 'property_template.WELCOME';

	/** the column name for the DESCRIPTION field */
	const DESCRIPTION = 'property_template.DESCRIPTION';

	/** the column name for the ANNOUNCEMENTS field */
	const ANNOUNCEMENTS = 'property_template.ANNOUNCEMENTS';

	/** the column name for the STYLE_COLOR field */
	const STYLE_COLOR = 'property_template.STYLE_COLOR';

	/** the column name for the BACKGROUND_COLOR field */
	const BACKGROUND_COLOR = 'property_template.BACKGROUND_COLOR';

	/** the column name for the CHAT field */
	const CHAT = 'property_template.CHAT';

	/** the column name for the RENTALAPP_FILE field */
	const RENTALAPP_FILE = 'property_template.RENTALAPP_FILE';

	/** the column name for the MAP_HTML field */
	const MAP_HTML = 'property_template.MAP_HTML';

	/** the column name for the MAP_FRAME_SRC field */
	const MAP_FRAME_SRC = 'property_template.MAP_FRAME_SRC';

	/** the column name for the COMMUNITY_IMAGE field */
	const COMMUNITY_IMAGE = 'property_template.COMMUNITY_IMAGE';

	/** the column name for the COMMUNITY_DESCRIPTION field */
	const COMMUNITY_DESCRIPTION = 'property_template.COMMUNITY_DESCRIPTION';

	/** the column name for the COMMUNITY_ATTRACTIONS_LIST field */
	const COMMUNITY_ATTRACTIONS_LIST = 'property_template.COMMUNITY_ATTRACTIONS_LIST';

	/** the column name for the CUSTOM_PAGE_NAME field */
	const CUSTOM_PAGE_NAME = 'property_template.CUSTOM_PAGE_NAME';

	/** the column name for the CUSTOM_PAGE_PERMA_LINK field */
	const CUSTOM_PAGE_PERMA_LINK = 'property_template.CUSTOM_PAGE_PERMA_LINK';

	/** the column name for the CUSTOM_PAGE_CONTENT field */
	const CUSTOM_PAGE_CONTENT = 'property_template.CUSTOM_PAGE_CONTENT';

	/** the column name for the HOME_FLASH field */
	const HOME_FLASH = 'property_template.HOME_FLASH';

	/** the column name for the TRACKING_CODE field */
	const TRACKING_CODE = 'property_template.TRACKING_CODE';

	/** the column name for the CONTACT_EMAIL_TEXT field */
	const CONTACT_EMAIL_TEXT = 'property_template.CONTACT_EMAIL_TEXT';

	/** the column name for the SHOW_WALKSCORE field */
	const SHOW_WALKSCORE = 'property_template.SHOW_WALKSCORE';

	/** the column name for the EMAIL field */
	const EMAIL = 'property_template.EMAIL';

	/** the column name for the FACEBOOK_URL field */
	const FACEBOOK_URL = 'property_template.FACEBOOK_URL';

	/** the column name for the ACACIA_HOME1_DESC field */
	const ACACIA_HOME1_DESC = 'property_template.ACACIA_HOME1_DESC';

	/** the column name for the ACACIA_FEATURES_DESC field */
	const ACACIA_FEATURES_DESC = 'property_template.ACACIA_FEATURES_DESC';

	/** the column name for the ACACIA_HOME2_DESC field */
	const ACACIA_HOME2_DESC = 'property_template.ACACIA_HOME2_DESC';

	/** the column name for the ACACIA_HOME3_DESC field */
	const ACACIA_HOME3_DESC = 'property_template.ACACIA_HOME3_DESC';

	/** the column name for the ACACIA_FLOORPLAN_DESC field */
	const ACACIA_FLOORPLAN_DESC = 'property_template.ACACIA_FLOORPLAN_DESC';

	/** the column name for the ACACIA_EBROCHURE_DESC field */
	const ACACIA_EBROCHURE_DESC = 'property_template.ACACIA_EBROCHURE_DESC';

	/** the column name for the LATITUDE field */
	const LATITUDE = 'property_template.LATITUDE';

	/** the column name for the LONGITUDE field */
	const LONGITUDE = 'property_template.LONGITUDE';

	/**
	 * An identiy map to hold any loaded instances of PropertyTemplate objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array PropertyTemplate[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'PropertyId', 'LogoImage', 'HomeImage', 'Welcome', 'Description', 'Announcements', 'StyleColor', 'BackgroundColor', 'Chat', 'RentalappFile', 'MapHtml', 'MapFrameSrc', 'CommunityImage', 'CommunityDescription', 'CommunityAttractionsList', 'CustomPageName', 'CustomPagePermaLink', 'CustomPageContent', 'HomeFlash', 'TrackingCode', 'ContactEmailText', 'ShowWalkscore', 'Email', 'FacebookUrl', 'AcaciaHome1Desc', 'AcaciaFeaturesDesc', 'AcaciaHome2Desc', 'AcaciaHome3Desc', 'AcaciaFloorplanDesc', 'AcaciaEbrochureDesc', 'Latitude', 'Longitude', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'propertyId', 'logoImage', 'homeImage', 'welcome', 'description', 'announcements', 'styleColor', 'backgroundColor', 'chat', 'rentalappFile', 'mapHtml', 'mapFrameSrc', 'communityImage', 'communityDescription', 'communityAttractionsList', 'customPageName', 'customPagePermaLink', 'customPageContent', 'homeFlash', 'trackingCode', 'contactEmailText', 'showWalkscore', 'email', 'facebookUrl', 'acaciaHome1Desc', 'acaciaFeaturesDesc', 'acaciaHome2Desc', 'acaciaHome3Desc', 'acaciaFloorplanDesc', 'acaciaEbrochureDesc', 'latitude', 'longitude', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::PROPERTY_ID, self::LOGO_IMAGE, self::HOME_IMAGE, self::WELCOME, self::DESCRIPTION, self::ANNOUNCEMENTS, self::STYLE_COLOR, self::BACKGROUND_COLOR, self::CHAT, self::RENTALAPP_FILE, self::MAP_HTML, self::MAP_FRAME_SRC, self::COMMUNITY_IMAGE, self::COMMUNITY_DESCRIPTION, self::COMMUNITY_ATTRACTIONS_LIST, self::CUSTOM_PAGE_NAME, self::CUSTOM_PAGE_PERMA_LINK, self::CUSTOM_PAGE_CONTENT, self::HOME_FLASH, self::TRACKING_CODE, self::CONTACT_EMAIL_TEXT, self::SHOW_WALKSCORE, self::EMAIL, self::FACEBOOK_URL, self::ACACIA_HOME1_DESC, self::ACACIA_FEATURES_DESC, self::ACACIA_HOME2_DESC, self::ACACIA_HOME3_DESC, self::ACACIA_FLOORPLAN_DESC, self::ACACIA_EBROCHURE_DESC, self::LATITUDE, self::LONGITUDE, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'property_id', 'logo_image', 'home_image', 'welcome', 'description', 'announcements', 'style_color', 'background_color', 'chat', 'rentalapp_file', 'map_html', 'map_frame_src', 'community_image', 'community_description', 'community_attractions_list', 'custom_page_name', 'custom_page_perma_link', 'custom_page_content', 'home_flash', 'tracking_code', 'contact_email_text', 'show_walkscore', 'email', 'facebook_url', 'acacia_home1_desc', 'acacia_features_desc', 'acacia_home2_desc', 'acacia_home3_desc', 'acacia_floorplan_desc', 'acacia_ebrochure_desc', 'latitude', 'longitude', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'PropertyId' => 1, 'LogoImage' => 2, 'HomeImage' => 3, 'Welcome' => 4, 'Description' => 5, 'Announcements' => 6, 'StyleColor' => 7, 'BackgroundColor' => 8, 'Chat' => 9, 'RentalappFile' => 10, 'MapHtml' => 11, 'MapFrameSrc' => 12, 'CommunityImage' => 13, 'CommunityDescription' => 14, 'CommunityAttractionsList' => 15, 'CustomPageName' => 16, 'CustomPagePermaLink' => 17, 'CustomPageContent' => 18, 'HomeFlash' => 19, 'TrackingCode' => 20, 'ContactEmailText' => 21, 'ShowWalkscore' => 22, 'Email' => 23, 'FacebookUrl' => 24, 'AcaciaHome1Desc' => 25, 'AcaciaFeaturesDesc' => 26, 'AcaciaHome2Desc' => 27, 'AcaciaHome3Desc' => 28, 'AcaciaFloorplanDesc' => 29, 'AcaciaEbrochureDesc' => 30, 'Latitude' => 31, 'Longitude' => 32, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'propertyId' => 1, 'logoImage' => 2, 'homeImage' => 3, 'welcome' => 4, 'description' => 5, 'announcements' => 6, 'styleColor' => 7, 'backgroundColor' => 8, 'chat' => 9, 'rentalappFile' => 10, 'mapHtml' => 11, 'mapFrameSrc' => 12, 'communityImage' => 13, 'communityDescription' => 14, 'communityAttractionsList' => 15, 'customPageName' => 16, 'customPagePermaLink' => 17, 'customPageContent' => 18, 'homeFlash' => 19, 'trackingCode' => 20, 'contactEmailText' => 21, 'showWalkscore' => 22, 'email' => 23, 'facebookUrl' => 24, 'acaciaHome1Desc' => 25, 'acaciaFeaturesDesc' => 26, 'acaciaHome2Desc' => 27, 'acaciaHome3Desc' => 28, 'acaciaFloorplanDesc' => 29, 'acaciaEbrochureDesc' => 30, 'latitude' => 31, 'longitude' => 32, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::PROPERTY_ID => 1, self::LOGO_IMAGE => 2, self::HOME_IMAGE => 3, self::WELCOME => 4, self::DESCRIPTION => 5, self::ANNOUNCEMENTS => 6, self::STYLE_COLOR => 7, self::BACKGROUND_COLOR => 8, self::CHAT => 9, self::RENTALAPP_FILE => 10, self::MAP_HTML => 11, self::MAP_FRAME_SRC => 12, self::COMMUNITY_IMAGE => 13, self::COMMUNITY_DESCRIPTION => 14, self::COMMUNITY_ATTRACTIONS_LIST => 15, self::CUSTOM_PAGE_NAME => 16, self::CUSTOM_PAGE_PERMA_LINK => 17, self::CUSTOM_PAGE_CONTENT => 18, self::HOME_FLASH => 19, self::TRACKING_CODE => 20, self::CONTACT_EMAIL_TEXT => 21, self::SHOW_WALKSCORE => 22, self::EMAIL => 23, self::FACEBOOK_URL => 24, self::ACACIA_HOME1_DESC => 25, self::ACACIA_FEATURES_DESC => 26, self::ACACIA_HOME2_DESC => 27, self::ACACIA_HOME3_DESC => 28, self::ACACIA_FLOORPLAN_DESC => 29, self::ACACIA_EBROCHURE_DESC => 30, self::LATITUDE => 31, self::LONGITUDE => 32, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'property_id' => 1, 'logo_image' => 2, 'home_image' => 3, 'welcome' => 4, 'description' => 5, 'announcements' => 6, 'style_color' => 7, 'background_color' => 8, 'chat' => 9, 'rentalapp_file' => 10, 'map_html' => 11, 'map_frame_src' => 12, 'community_image' => 13, 'community_description' => 14, 'community_attractions_list' => 15, 'custom_page_name' => 16, 'custom_page_perma_link' => 17, 'custom_page_content' => 18, 'home_flash' => 19, 'tracking_code' => 20, 'contact_email_text' => 21, 'show_walkscore' => 22, 'email' => 23, 'facebook_url' => 24, 'acacia_home1_desc' => 25, 'acacia_features_desc' => 26, 'acacia_home2_desc' => 27, 'acacia_home3_desc' => 28, 'acacia_floorplan_desc' => 29, 'acacia_ebrochure_desc' => 30, 'latitude' => 31, 'longitude' => 32, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. PropertyTemplatePeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(PropertyTemplatePeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(PropertyTemplatePeer::ID);
		$criteria->addSelectColumn(PropertyTemplatePeer::PROPERTY_ID);
		$criteria->addSelectColumn(PropertyTemplatePeer::LOGO_IMAGE);
		$criteria->addSelectColumn(PropertyTemplatePeer::HOME_IMAGE);
		$criteria->addSelectColumn(PropertyTemplatePeer::WELCOME);
		$criteria->addSelectColumn(PropertyTemplatePeer::DESCRIPTION);
		$criteria->addSelectColumn(PropertyTemplatePeer::ANNOUNCEMENTS);
		$criteria->addSelectColumn(PropertyTemplatePeer::STYLE_COLOR);
		$criteria->addSelectColumn(PropertyTemplatePeer::BACKGROUND_COLOR);
		$criteria->addSelectColumn(PropertyTemplatePeer::CHAT);
		$criteria->addSelectColumn(PropertyTemplatePeer::RENTALAPP_FILE);
		$criteria->addSelectColumn(PropertyTemplatePeer::MAP_HTML);
		$criteria->addSelectColumn(PropertyTemplatePeer::MAP_FRAME_SRC);
		$criteria->addSelectColumn(PropertyTemplatePeer::COMMUNITY_IMAGE);
		$criteria->addSelectColumn(PropertyTemplatePeer::COMMUNITY_DESCRIPTION);
		$criteria->addSelectColumn(PropertyTemplatePeer::COMMUNITY_ATTRACTIONS_LIST);
		$criteria->addSelectColumn(PropertyTemplatePeer::CUSTOM_PAGE_NAME);
		$criteria->addSelectColumn(PropertyTemplatePeer::CUSTOM_PAGE_PERMA_LINK);
		$criteria->addSelectColumn(PropertyTemplatePeer::CUSTOM_PAGE_CONTENT);
		$criteria->addSelectColumn(PropertyTemplatePeer::HOME_FLASH);
		$criteria->addSelectColumn(PropertyTemplatePeer::TRACKING_CODE);
		$criteria->addSelectColumn(PropertyTemplatePeer::CONTACT_EMAIL_TEXT);
		$criteria->addSelectColumn(PropertyTemplatePeer::SHOW_WALKSCORE);
		$criteria->addSelectColumn(PropertyTemplatePeer::EMAIL);
		$criteria->addSelectColumn(PropertyTemplatePeer::FACEBOOK_URL);
		$criteria->addSelectColumn(PropertyTemplatePeer::ACACIA_HOME1_DESC);
		$criteria->addSelectColumn(PropertyTemplatePeer::ACACIA_FEATURES_DESC);
		$criteria->addSelectColumn(PropertyTemplatePeer::ACACIA_HOME2_DESC);
		$criteria->addSelectColumn(PropertyTemplatePeer::ACACIA_HOME3_DESC);
		$criteria->addSelectColumn(PropertyTemplatePeer::ACACIA_FLOORPLAN_DESC);
		$criteria->addSelectColumn(PropertyTemplatePeer::ACACIA_EBROCHURE_DESC);
		$criteria->addSelectColumn(PropertyTemplatePeer::LATITUDE);
		$criteria->addSelectColumn(PropertyTemplatePeer::LONGITUDE);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PropertyTemplatePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PropertyTemplatePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(PropertyTemplatePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePropertyTemplatePeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     PropertyTemplate
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = PropertyTemplatePeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return PropertyTemplatePeer::populateObjects(PropertyTemplatePeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PropertyTemplatePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			PropertyTemplatePeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePropertyTemplatePeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      PropertyTemplate $value A PropertyTemplate object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(PropertyTemplate $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A PropertyTemplate object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof PropertyTemplate) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or PropertyTemplate object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     PropertyTemplate Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to property_template
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = PropertyTemplatePeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = PropertyTemplatePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = PropertyTemplatePeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				PropertyTemplatePeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Property table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinProperty(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PropertyTemplatePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PropertyTemplatePeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PropertyTemplatePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(PropertyTemplatePeer::PROPERTY_ID, PropertyPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePropertyTemplatePeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of PropertyTemplate objects pre-filled with their Property objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of PropertyTemplate objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinProperty(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PropertyTemplatePeer::addSelectColumns($criteria);
		$startcol = (PropertyTemplatePeer::NUM_COLUMNS - PropertyTemplatePeer::NUM_LAZY_LOAD_COLUMNS);
		PropertyPeer::addSelectColumns($criteria);

		$criteria->addJoin(PropertyTemplatePeer::PROPERTY_ID, PropertyPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePropertyTemplatePeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PropertyTemplatePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PropertyTemplatePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = PropertyTemplatePeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PropertyTemplatePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = PropertyPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = PropertyPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = PropertyPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					PropertyPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded
				
				// Add the $obj1 (PropertyTemplate) to $obj2 (Property)
				$obj2->addPropertyTemplate($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PropertyTemplatePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PropertyTemplatePeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PropertyTemplatePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(PropertyTemplatePeer::PROPERTY_ID, PropertyPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePropertyTemplatePeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of PropertyTemplate objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of PropertyTemplate objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PropertyTemplatePeer::addSelectColumns($criteria);
		$startcol2 = (PropertyTemplatePeer::NUM_COLUMNS - PropertyTemplatePeer::NUM_LAZY_LOAD_COLUMNS);

		PropertyPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (PropertyPeer::NUM_COLUMNS - PropertyPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(PropertyTemplatePeer::PROPERTY_ID, PropertyPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePropertyTemplatePeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PropertyTemplatePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PropertyTemplatePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = PropertyTemplatePeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PropertyTemplatePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Property rows

			$key2 = PropertyPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = PropertyPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = PropertyPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					PropertyPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (PropertyTemplate) to the collection in $obj2 (Property)
				$obj2->addPropertyTemplate($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BasePropertyTemplatePeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BasePropertyTemplatePeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new PropertyTemplateTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? PropertyTemplatePeer::CLASS_DEFAULT : PropertyTemplatePeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a PropertyTemplate or Criteria object.
	 *
	 * @param      mixed $values Criteria or PropertyTemplate object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePropertyTemplatePeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BasePropertyTemplatePeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(PropertyTemplatePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from PropertyTemplate object
		}

		if ($criteria->containsKey(PropertyTemplatePeer::ID) && $criteria->keyContainsValue(PropertyTemplatePeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.PropertyTemplatePeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePropertyTemplatePeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BasePropertyTemplatePeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a PropertyTemplate or Criteria object.
	 *
	 * @param      mixed $values Criteria or PropertyTemplate object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePropertyTemplatePeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BasePropertyTemplatePeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(PropertyTemplatePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(PropertyTemplatePeer::ID);
			$selectCriteria->add(PropertyTemplatePeer::ID, $criteria->remove(PropertyTemplatePeer::ID), $comparison);

		} else { // $values is PropertyTemplate object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasePropertyTemplatePeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BasePropertyTemplatePeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the property_template table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PropertyTemplatePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(PropertyTemplatePeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			PropertyTemplatePeer::clearInstancePool();
			PropertyTemplatePeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a PropertyTemplate or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or PropertyTemplate object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(PropertyTemplatePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			PropertyTemplatePeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof PropertyTemplate) { // it's a model object
			// invalidate the cache for this single object
			PropertyTemplatePeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(PropertyTemplatePeer::ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				PropertyTemplatePeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			PropertyTemplatePeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given PropertyTemplate object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      PropertyTemplate $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(PropertyTemplate $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(PropertyTemplatePeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(PropertyTemplatePeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(PropertyTemplatePeer::DATABASE_NAME, PropertyTemplatePeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     PropertyTemplate
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = PropertyTemplatePeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(PropertyTemplatePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(PropertyTemplatePeer::DATABASE_NAME);
		$criteria->add(PropertyTemplatePeer::ID, $pk);

		$v = PropertyTemplatePeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PropertyTemplatePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(PropertyTemplatePeer::DATABASE_NAME);
			$criteria->add(PropertyTemplatePeer::ID, $pks, Criteria::IN);
			$objs = PropertyTemplatePeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BasePropertyTemplatePeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BasePropertyTemplatePeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BasePropertyTemplatePeer::buildTableMap();

