<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/10/27 19:17:08
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'manager',
      ),
    ),
  ),
);
