<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/27 19:17:08
sfConfig::add(array(
  'mod_property_photos_enabled' => true,
  'mod_property_photos_view_class' => 'sfPHP',
  'mod_property_photos_is_internal' => false,
));
