<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/27 17:57:03
sfConfig::add(array(
  'mod_default_enabled' => true,
  'mod_default_view_class' => 'sfPHP',
  'mod_default_is_internal' => false,
));
