generator:
  class:              DbFinderAdminGenerator
  param:
    model_class:      PropertyBlogarticle
    theme:            default
    list:
      title: Property Blog Articles List
      fields:
        property: { sort_method: orderByProperty }
        property_id:
          params: 
            peer_method: getAll
      display: [property, title, perma_link]
      filters: [property_id]
      object_actions:
        _edit: false
        _delete: false
#_edit_form.php template overrides generator
    edit:
      title: Edit Blog Articles
      fields:
        title: { params: size=80x10 }
        perma_link: { params: size=80x10 }
        article_image1: { type: admin_input_file_tag, upload_dir: blogarticles, params: include_link=blogarticles include_remove=true}
        article_image2: { type: admin_input_file_tag, upload_dir: blogarticles, params: include_link=blogarticles include_remove=true}
        article_content: { params: rich=true size=120x30 }
        property_id:
          params: 
            peer_method: getAll
      display: [property_id, title, perma_link, article_image1, article_image2, article_content]