default:
  http_metas:
    content-type: text/html

  metas:
    title:        AMCapartments.com | Find an Apartment Today | Find Apartments for Rent, Houses, Condos and Townhomes | Rental Listings
    description:  Find and rent apartments, condos and townhomes. View floor plans and photos.
    keywords:     rent, apartments, houses, condo, townhomes, townhouses, apartments for rent, apartment finder, for rent by owner
    language:     en
    robots:       index, follow


  stylesheets:    [-main, -styles, llciframe]

  javascripts:    [common.js]

  layout: llciframe