<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/08 13:34:47
sfConfig::add(array(
  'mod_floorplans_enabled' => true,
  'mod_floorplans_view_class' => 'sfPHP',
  'mod_floorplans_is_internal' => false,
));
