<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/08 13:47:34
sfConfig::add(array(
  'mod_ebrochure_enabled' => true,
  'mod_ebrochure_view_class' => 'sfPHP',
  'mod_ebrochure_is_internal' => false,
));
