<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/03/08 13:36:49
$this->security = array (
  'forgotpassword' => 
  array (
    'is_secure' => false,
  ),
  'forgotuserid' => 
  array (
    'is_secure' => false,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
