<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/08 13:35:07
sfConfig::add(array(
  'mod_contact_enabled' => true,
  'mod_contact_view_class' => 'sfPHP',
  'mod_contact_is_internal' => false,
));
