<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/08 13:44:39
sfConfig::add(array(
  'mod_ourpage_enabled' => true,
  'mod_ourpage_view_class' => 'sfPHP',
  'mod_ourpage_is_internal' => false,
));
