<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/09 09:00:10
sfConfig::add(array(
  'mod_blog_enabled' => true,
  'mod_blog_view_class' => 'sfPHP',
  'mod_blog_is_internal' => false,
));
