<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/08 13:36:39
sfConfig::add(array(
  'mod_community_enabled' => true,
  'mod_community_view_class' => 'sfPHP',
  'mod_community_is_internal' => false,
));
