<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/08 13:36:49
sfConfig::add(array(
  'mod_residents_enabled' => true,
  'mod_residents_view_class' => 'sfPHP',
  'mod_residents_is_internal' => false,
));
