<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/08 14:14:42
sfConfig::add(array(
  'mod_sitemap_enabled' => true,
  'mod_sitemap_view_class' => 'sfPHP',
  'mod_sitemap_is_internal' => false,
));
