<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/08 13:34:44
sfConfig::add(array(
  'mod_features_enabled' => true,
  'mod_features_view_class' => 'sfPHP',
  'mod_features_is_internal' => false,
));
