generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Resident
    theme:            default
    list:
      title: Resident List
      display: [first_name, last_name, email, property, status, created_at]
      filters: [email, last_name, first_name, status_id, created_at]
      object_actions:
        _edit: false
        _delete: false

    edit:
      title: Edit Residents
      fields:
        created_at {type: plain}
      display: [first_name, last_name, email, password, tenantid, property_id, status_id]