# default rules
homepage:
  url:   /
  param: { module: default, action: index }
  
default_index:
  url:   /:module
  param: { action: index }

property_by_permalink:
  url: /:state/:city/:perma/:type/:id
  param: { module: property, action: list, view: detail }

default:
  url:   /:module/:action/*

  