generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      OtherFeature
    theme:            default
    list:
      title: Other Feature List
      display: [name]
      filters: [name]
      object_actions:
        _edit: false
        _delete: false

    edit:
      title: Edit Other Feature
      display: [name]