<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2012/10/27 19:17:08
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoProperty_photos/actions/actions.class.php');

