generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      PropertyFloorplan
    theme:            default
    list:
      title: Property Floorplan List
      fields:
        property: { sort_method: orderByProperty }
        property_id:
          params:
            peer_method: getAll
      display: [name, property, bedrooms, price, lease_term, display_order]
      filters: [name, property_id]
      object_actions:
        _edit: false
        _delete: false

    edit:
      title: Edit Property Floorplan
      fields:
        image: { type: admin_input_file_tag, upload_dir: floorplans, params: include_link=floorplans include_remove=true}
      display: [name, property_id, bedrooms, bathrooms, square_feet, price, lease_term, deposit, availability_link, display_order, image]