<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:15:13
sfConfig::add(array(
  'mod_property_photos_enabled' => true,
  'mod_property_photos_view_class' => 'sfPHP',
  'mod_property_photos_is_internal' => false,
));
