<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/25 09:43:30
sfConfig::add(array(
  'mod_property_blogarticles_enabled' => true,
  'mod_property_blogarticles_view_class' => 'sfPHP',
  'mod_property_blogarticles_is_internal' => false,
));
