<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/02/21 14:49:13
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
      ),
    ),
  ),
);
