<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2017/01/19 13:34:15
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoProperties/actions/actions.class.php');

