<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/01/19 15:07:56
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
      ),
    ),
  ),
);
