<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 15:07:56
sfConfig::add(array(
  'mod_property_floorplans_enabled' => true,
  'mod_property_floorplans_view_class' => 'sfPHP',
  'mod_property_floorplans_is_internal' => false,
));
