<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2017/01/23 15:36:22
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoCommunity_features/actions/actions.class.php');

