<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/03/05 21:15:31
sfConfig::add(array(
  'mod_other_features_enabled' => true,
  'mod_other_features_view_class' => 'sfPHP',
  'mod_other_features_is_internal' => false,
));
