<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2017/01/24 10:36:33
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoApartment_features/actions/actions.class.php');

