<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/02/21 14:49:13
sfConfig::add(array(
  'mod_residents_enabled' => true,
  'mod_residents_view_class' => 'sfPHP',
  'mod_residents_is_internal' => false,
));
