<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/23 15:36:22
sfConfig::add(array(
  'mod_community_features_enabled' => true,
  'mod_community_features_view_class' => 'sfPHP',
  'mod_community_features_is_internal' => false,
));
