<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2017/01/31 12:18:29
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoUsers/actions/actions.class.php');

