<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 13:34:15
sfConfig::add(array(
  'mod_properties_enabled' => true,
  'mod_properties_view_class' => 'sfPHP',
  'mod_properties_is_internal' => false,
));
