<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/19 10:12:01
sfConfig::add(array(
  'mod_property_templates_enabled' => true,
  'mod_property_templates_view_class' => 'sfPHP',
  'mod_property_templates_is_internal' => false,
));
