<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/01/24 10:36:33
sfConfig::add(array(
  'mod_apartment_features_enabled' => true,
  'mod_apartment_features_view_class' => 'sfPHP',
  'mod_apartment_features_is_internal' => false,
));
