<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2017/03/05 21:15:31
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoOther_features/actions/actions.class.php');

