<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/26 18:02:22
sfConfig::add(array(
  'mod_contact_enabled' => true,
  'mod_contact_view_class' => 'sfPHP',
  'mod_contact_is_internal' => false,
));
