<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/26 18:02:57
sfConfig::add(array(
  'mod_termsofuse_enabled' => true,
  'mod_termsofuse_view_class' => 'sfPHP',
  'mod_termsofuse_is_internal' => false,
));
