<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/26 18:01:40
sfConfig::add(array(
  'mod_residents_enabled' => true,
  'mod_residents_view_class' => 'sfPHP',
  'mod_residents_is_internal' => false,
));
