<?php

require 'lib/model/om/BasePropertyCommunityMapPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'property_community_map' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Feb 27 21:42:19 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PropertyCommunityMapPeer extends BasePropertyCommunityMapPeer {

} // PropertyCommunityMapPeer
