<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/27 15:35:01
sfConfig::add(array(
  'mod_floorplans_enabled' => true,
  'mod_floorplans_view_class' => 'sfPHP',
  'mod_floorplans_is_internal' => false,
));
