<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/26 19:53:17
sfConfig::add(array(
  'mod_sfcaptchagd_enabled' => true,
  'mod_sfcaptchagd_view_class' => 'sfPHP',
  'mod_sfcaptchagd_is_internal' => false,
));
