# default rules
highgrovewildreed:
  url: /highgroveWildreed
  param: { module: highgrovewildreed, action: index }
bloomingdale:
  url: /Bloomingdale
  param: { module: bloomingdale, action: index }
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }
  
property_list_city:
  url: /city/:code
  param: { module: property, action: list, view: city }
  
property_list_state:
  url: /state/:code
  param: { module: property, action: list, view: state }
  
property_by_permalink:
  url: /:state/:city/:perma/:type/:id
  param: { module: property, action: list, view: detail }

default:
  url:   /:module/:action/*
