#mobileSuccess:
#  stylesheets: [-*, http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.css, mobilemain.css]
#  javascripts: [-*, http://code.jquery.com/jquery-1.7.1.min.js, http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js, http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js, photos.js]
acaciaSuccess:
  stylesheets: [-*, acacia.css, jquery.lightbox-0.5.css]
  javascripts: [-*, https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, jquery.lightbox-0.5.min.js, acacia.js]
jspSuccess:
  stylesheets: [-*, http://fonts.googleapis.com/css?family=Lato:300, jsp.css, jquery.lightbox-0.5.css]
  javascripts: [-*, https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js, jquery.lightbox-0.5.min.js, jsp.js]
