property_template:
  class: sfPropelRouteCollection
  options:
    model:                PropertyTemplate
    module:               property_temaplates
    prefix_path:          /property_temaplates
    column:               id
    with_wildcard_routes: true

propertytemplate:
  class: sfPropelRouteCollection
  options:
    model:                propertytemplate
    module:               propertytemplate
    prefix_path:          /propertytemplate
    column:               id
    with_wildcard_routes: true

user:
  class: sfPropelRouteCollection
  options:
    model:                User
    module:               user
    prefix_path:          user
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
