<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/06/19 12:05:03

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=amcapartments_com_dev;host=localhost',
  'username' => 'amcapartmentsdev',
  'password' => 'Um5AvWNV',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
