<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/19 12:06:08
sfConfig::add(array(
  'mod_photos_enabled' => true,
  'mod_photos_view_class' => 'sfPHP',
  'mod_photos_is_internal' => false,
));
