<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/19 12:05:03
sfConfig::add(array(
  'mod_floorplans_enabled' => true,
  'mod_floorplans_view_class' => 'sfPHP',
  'mod_floorplans_is_internal' => false,
));
