<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/19 12:19:44
sfConfig::add(array(
  'mod_contact_enabled' => true,
  'mod_contact_view_class' => 'sfPHP',
  'mod_contact_is_internal' => false,
));
