<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/19 12:19:45
sfConfig::add(array(
  'mod_sfcaptchagd_enabled' => true,
  'mod_sfcaptchagd_view_class' => 'sfPHP',
  'mod_sfcaptchagd_is_internal' => false,
));
