dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=amcapartments_com_dev;host=localhost
      username:   amcapartmentsdev
      password:   Um5AvWNV
      encoding:   utf8
      persistent: true
      pooling:    true
