default:
  http_metas:
    content-type: text/html

  metas:
    #title:        "AMC Appartments"
    #description:  symfony project
    #keywords:
    #language:     en
    #robots:       index, follow

  stylesheets:
    - lightbox
    - styles
    - print: { media: print }
    - ie6-styles: { condition: lte IE 6 }

  javascripts:
    - common
    - prototype
    - scriptaculous
    - builder
    - effects
    - lightbox
    - unitpngfix: { condition: lte IE 6 }

  has_layout:     true
  layout:         layout