var map_config = {
  'default':{
    'borderColor':'#FFFFFF', //inter-state borders
    'lakesColor':'#ACE9FC', // lakes color
    'namesColor':'#FFFFFF', //color of short names
    'mapShadow':'#000', //shadow color below the map
    'shadowOpacity':'50', //shadow opacity, value, 0-100
    'hoverShadow':'#666666', //tooltip shadow color
  },
  'map_1':{
    'hover': 'ALABAMA', //state hover content
    'url':'/state/AL', //Goto URL
    'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
    'upColor':'#58741f', //state's color when page loads
    'overColor':'#50b2c1', //state's color when mouse hover
    'downColor':'#f6901e',//state's color when mouse clicking
    'enable':false,//true/false to enable/disable this state
  },
  'map_2':{
    'hover': 'ALASKA',
    'url':'/state/AK',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_3':{
    'hover': 'ARIZONA',
    'url':'/state/AZ',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_4':{
    'hover': 'ARKANSAS',
    'url':'/state/AK',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_5':{
    'hover': 'CALIFORNIA',
    'url':'/state/CA',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_6':{
    'hover': 'COLORADO',
    'url':'/state/CO',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_7':{
    'hover': 'CONNECTICUT',
    'url':'/state/CT',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_8':{
    'hover': 'DELAWARE',
    'url':'/state/DE',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_9':{
    'hover': 'FLORIDA',
    'url':'/state/FL',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_10':{
    'hover': 'GEORGIA',
    'url':'/state/GA',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_11':{
    'hover': 'HAWAII',
    'url':'/state/HI',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_12':{
    'hover': 'IDAHO',
    'url':'/state/ID',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_13':{
    'hover': 'ILLINOIS',
    'url':'/state/IL',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_14':{
    'hover': 'INDIANA',
    'url':'/state/IN',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_15':{
    'hover': 'IOWA',
    'url':'/state/IA',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_16':{
    'hover': 'KANSAS',
    'url':'/state/KS',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_17':{
    'hover': 'KENTUCKY',
    'url':'/state/KY',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_18':{
    'hover': 'LOUISIANA',
    'url':'/state/LA',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_19':{
    'hover': 'MAINE',
    'url':'/state/ME',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_20':{
    'hover': 'MARYLAND',
    'url':'/state/MD',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_21':{
    'hover': 'MASSACHUSETTS',
    'url':'/state/MA',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_22':{
    'hover': 'MICHIGAN',
    'url':'/state/MI',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':true,
  },
  'map_23':{
    'hover': 'MINNESOTA',
    'url':'/state/MN',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_24':{
    'hover': 'MISSISSIPPI',
    'url':'/state/MS',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_25':{
    'hover': 'MISSOURI',
    'url':'/state/MO',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_26':{
    'hover': 'MONTANA',
    'url':'/state/MT',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_27':{
    'hover': 'NEBRASKA',
    'url':'/state/NE',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_28':{
    'hover': 'NEVADA',
    'url':'/state/NV',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_29':{
    'hover': 'NEW HAMPSHIRE',
    'url':'/state/NH',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_30':{
    'hover': 'NEW JERSEY',
    'url':'/state/NJ',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_31':{
    'hover': 'NEW MEXICO',
    'url':'/state/NM',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_32':{
    'hover': 'NEW YORK',
    'url':'/state/NY',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_33':{
    'hover': 'NORTH CAROLINA',
    'url':'/state/NC',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_34':{
    'hover': 'NORTH DAKOTA',
    'url':'/state/ND',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_35':{
    'hover': 'OHIO',
    'url':'/state/OH',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_36':{
    'hover': 'OKLAHOMA',
    'url':'/state/OK',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_37':{
    'hover': 'OREGON',
    'url':'/state/OR',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_38':{
    'hover': 'PENNSYLVANIA',
    'url':'/state/PA',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_39':{
    'hover': 'RHODE ISLAND',
    'url':'/state/RI',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_40':{
    'hover': 'SOUTH CAROLINA',
    'url':'/state/SC',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_41':{
    'hover': 'SOUTH DAKOTA',
    'url':'/state/SD',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#f6901e',
    'enable':false,
  },
  'map_42':{
    'hover': 'TENNESSEE',
    'url':'/apartments/Tennessee/rentals/TN/',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_43':{
    'hover': 'TEXAS',
    'url':'/state/TX',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_44':{
    'hover': 'UTAH',
    'url':'/state/UT',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_45':{
    'hover': 'VERMONT',
    'url':'/state/VT',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_46':{
    'hover': 'VIRGINIA',
    'url':'/state/VA',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_47':{
    'hover': 'WASHINGTON',
    'url':'/state/WA',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
  'map_48':{
    'hover': 'WEST VIRGINIA',
    'url':'/state/WV',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_49':{
    'hover': 'WISCONSIN',
    'url':'/state/WI',
    'target':'same_window',
    'upColor':'#58741f',
    'overColor':'#50b2c1',
    'downColor':'#993366',
    'enable':false,
  },
  'map_50':{
    'hover': 'WYOMING',
    'url':'/state/WY',
    'target':'same_window',
    'upColor':'#a4c93b',
    'overColor':'#50b2c1',
    'downColor':'#a4c93b',
    'enable':true,
  },
}
