<?php


/**
 * This class defines the structure of the 'property_community_map' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Mar  2 17:48:01 2017
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PropertyCommunityMapTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PropertyCommunityMapTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('property_community_map');
		$this->setPhpName('PropertyCommunityMap');
		$this->setClassname('PropertyCommunityMap');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 10, null);
		$this->addColumn('PROPERTY_ID', 'PropertyId', 'INTEGER', true, 10, null);
		$this->addColumn('TYPE', 'Type', 'CHAR', true, null, 'entertainment');
		$this->addColumn('NAME', 'Name', 'VARCHAR', false, 128, null);
		$this->addColumn('LATITUDE', 'Latitude', 'DECIMAL', false, 10, null);
		$this->addColumn('LONGITUDE', 'Longitude', 'DECIMAL', false, 10, null);
		$this->addColumn('URL', 'Url', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // PropertyCommunityMapTableMap
